
services:
  frontend:
    build:
      context: ./client  # Path to your Angular project directory
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Map Nginx default port to host
    environment:
      - VITE_API_URL=http://localhost:8002  # Set API URL to communicate with the backend
    depends_on:
      - backend  # Ensure backend starts before frontend
      

  backend:
    build:
      context: ./backend  # Path to your Django project directory
      dockerfile: Dockerfile
    ports:
      - "8002:8002"  # Map Django app port to host
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings  # Adjust to match your project settings module
    volumes:
      - ./backend:/app  # Bind mount for live code updates (optional)
      - ./backend/db.sqlite3:/app/db.sqlite3


networks:
  default:
    driver: bridge
